### PR TITLE
vim8 and vim-plug

### PR DESCRIPTION
**Pull request by nbouchinet**
You should rename `after` directory  into `plugin` for vim8 compatibility.

### CODE REVIEW

**Comment by pbondoer** [comment]
Shouldn't it work the same? As far as I know vim8 didn't remove the `after` directory?

Also, there's a good reason to use the `after` directory: if you are using it at a 42 campus, the `:Stdheader` definition causes conflicts and gives off an error. This isn't a problem in neovim, but is in vim.

**Comment by rpdelaney** [comment]
I don't see how this is an improvement. See #4 for background; this PR simply reverses that one, which will cause more annoyance when someone is trying to use 42header on campus.

**Comment by nbouchinet** [comment]
In my case, changing the after directory into plugin works with the 42 version of vim (7.4), vim 8 installed with brew and neovim. with the after directory it's seem's to work only with vim 7.4.

**Comment by rpdelaney** [comment]
Can you say more about what you mean by "works"?

**Comment by pbondoer** [comment]
See #6

**Pull request closed without merging**
